"""Build the text–facsimile alignment for poems with a team TEI (tei/genetic) and page images.

For each poem in pipeline/facsimile.json:
  - fetch the page images from WikiLeopardi (cached in pipeline/cache/images/);
  - write the web copies to public/img/facs/c{n}-{siglum}.jpg;
  - detect the verse cells inside the hand-marked region (none → the page is shown whole);
  - write tei/facsimile/c{n}.xml, check overlays in reports/facsimile/, and reports/facsimile_report.md,
    including a comparison of the team's N35c text with the WikiLeopardi base text.
"""
from __future__ import annotations

import json
import sys
import time
from pathlib import Path

import requests
from PIL import Image

from . import paths
from .build_base import base_verses
from .facsimile import build_facsimile_tei, detect_verse_zones, overlay, scale_zones, web_copy
from .harvest import API, USER_AGENT
from .manifest import load_manifest
from .team_tei import TeamPoem, read_team_poem

IMG_DIR = paths.ROOT / "public" / "img" / "facs"


def fetch_image(filename: str, cache_dir: Path) -> Path:
    """A WikiLeopardi file (e.g. InfinitoB26.jpg), downloaded once into the cache."""
    path = Path(cache_dir) / filename
    if path.exists():
        return path
    headers = {"User-Agent": USER_AGENT}
    params = {"action": "query", "titles": f"File:{filename}", "prop": "imageinfo", "iiprop": "url", "format": "json"}
    page = next(iter(requests.get(API, params=params, headers=headers, timeout=30).json()["query"]["pages"].values()))
    url = page["imageinfo"][0]["url"]
    time.sleep(0.5)
    data = requests.get(url, headers=headers, timeout=60)
    data.raise_for_status()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data.content)
    return path


def compare_with_base(team: TeamPoem, base: dict[int, str | None]) -> list[str]:
    """Verses where the team's N35c text differs from the WikiLeopardi base text."""
    out = []
    for n, segs in sorted(team.texts["N35c"]["verses"].items()):
        text = "".join(t for t, _ in segs)
        if base.get(n) is not None and text != base[n]:
            out.append(f"v{n}: team TEI {text!r} ≠ WikiLeopardi {base[n]!r}")
    return out


def build_poem(entry: dict, cfg: dict, report: list[str]) -> None:
    n = entry["n"]
    team = read_team_poem(paths.TEI_GENETIC / f"c{n}.xml")
    verses = len(team.texts["N35c"]["verses"])
    pages = {}
    report += [f"## {entry['roman']}. {entry['title']}", "", f"Images: {cfg['source']}.", ""]
    for siglum, page in cfg["pages"].items():
        original = Image.open(fetch_image(page["file"], paths.CACHE / "images"))
        zones = detect_verse_zones(original, page["region"], verses)
        web = web_copy(original)
        IMG_DIR.mkdir(parents=True, exist_ok=True)
        web.save(IMG_DIR / f"c{n}-{siglum}.jpg", quality=82, optimize=True)
        check = paths.REPORTS / "facsimile" / f"c{n}-{siglum}.jpg"
        check.parent.mkdir(parents=True, exist_ok=True)
        overlay(original, zones).save(check, quality=80)
        pages[siglum] = {
            "url": f"/img/facs/c{n}-{siglum}.jpg",
            "width": web.width,
            "height": web.height,
            "zones": scale_zones(zones, web.width / original.width) if zones else None,
        }
        state = f"{verses} verse zones" if zones else "no zones found: page shown whole"
        report.append(f"- {siglum} ({page['file']}): {state}; check image `{check.relative_to(paths.ROOT)}`")
    paths.TEI_FACS.mkdir(parents=True, exist_ok=True)
    (paths.TEI_FACS / f"c{n}.xml").write_bytes(build_facsimile_tei(entry, pages))
    diffs = compare_with_base(team, base_verses(paths.TEI_BASE / f"c{n}.xml"))
    report += ["", "Team N35c text compared with the WikiLeopardi base text:", ""]
    report += [f"- {d}" for d in diffs] or ["- identical"]
    report.append("")


def main() -> int:
    config = json.loads(paths.FACS_CONFIG.read_text(encoding="utf-8"))
    manifest = {e["n"]: e for e in load_manifest(paths.CANTI)}
    report = ["# Facsimile report", "", "Generated by `python -m leggo_pipeline.build_facsimile`.", ""]
    for key, cfg in config.items():
        build_poem(manifest[int(key)], cfg, report)
    (paths.REPORTS / "facsimile_report.md").write_text("\n".join(report) + "\n", encoding="utf-8")
    print("\n".join(report))
    return 0


if __name__ == "__main__":
    sys.exit(main())
