"""Build tei/traduzioni/{id}/c{n}.xml from the sources listed in pipeline/traduzioni.json.

The sources live outside the repository (the leopardi/ folder), so this runs locally; its output is committed.
"""
from __future__ import annotations

import json
import sys

from . import paths
from .manifest import load_manifest
from .translations import build_translation_tei, docx_heading, read_block, split_block

CONFIG = paths.ROOT / "pipeline" / "traduzioni.json"
SOURCES_ROOT = paths.ROOT.parent
OUT = paths.ROOT / "tei" / "traduzioni"


def build(config: dict, manifest: dict[int, dict]) -> list[str]:
    report = ["# Translations report", "", "Generated by `python -m leggo_pipeline.build_translations`.", ""]
    for key, entries in config.items():
        if key.startswith("_"):
            continue
        poem = manifest[int(key)]
        report += [f"## {poem['roman']}. {poem['title']}", "", "| id | lines | first line | last line |", "|---|---|---|---|"]
        notes = []
        for entry in entries:
            entry = dict(entry)
            if entry.get("bibl") is None:
                entry["bibl"] = docx_heading(entry["source"], SOURCES_ROOT)
            lines = read_block(entry["source"], SOURCES_ROOT)
            title, stanzas = split_block(lines, entry.get("title_lines", 1), entry.get("stanza_breaks", True))
            if not title and entry.get("title"):
                title = [entry["title"]]
            flat = [l for s in stanzas for l in s]
            if not flat:
                raise ValueError(f"{entry['id']}: no text in {entry['source']}")
            target = OUT / entry["id"] / f"c{poem['n']}.xml"
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(build_translation_tei(entry, poem, title, stanzas))
            report.append(f"| {entry['id']} | {len(flat)} | {flat[0][:60]} | {flat[-1][:60]} |")
            notes += [f"- {entry['id']}: {n}" for n in entry.get("notes", [])]
        report += ["", "Notes to review:", ""] + (notes or ["None."]) + [""]
    return report


def main() -> int:
    config = json.loads(CONFIG.read_text(encoding="utf-8"))
    manifest = {e["n"]: e for e in load_manifest(paths.CANTI)}
    report = build(config, manifest)
    (paths.REPORTS / "translations_report.md").write_text("\n".join(report) + "\n", encoding="utf-8")
    print("\n".join(report))
    return 0


if __name__ == "__main__":
    sys.exit(main())
